/**
 * `--ha-select-*` component tokens (53 keys), following the same
 * camelCase-key -> kebab-name convention and per-size suffix scheme as
 * `HA_INPUT_TOKENS`. Grouped as trigger (32), panel (7), and option (14).
 */
export const HA_SELECT_TOKENS = {
  // Trigger (32)
  bg: '--ha-select-bg',
  color: '--ha-select-color',
  border: '--ha-select-border',
  fontFamily: '--ha-select-font-family',
  fontWeight: '--ha-select-font-weight',
  lineHeight: '--ha-select-line-height',
  paddingSm: '--ha-select-padding-sm',
  paddingMd: '--ha-select-padding-md',
  paddingLg: '--ha-select-padding-lg',
  fontSm: '--ha-select-font-sm',
  fontMd: '--ha-select-font-md',
  fontLg: '--ha-select-font-lg',
  minHeightSm: '--ha-select-min-height-sm',
  minHeightMd: '--ha-select-min-height-md',
  minHeightLg: '--ha-select-min-height-lg',
  radiusSm: '--ha-select-radius-sm',
  radiusMd: '--ha-select-radius-md',
  radiusLg: '--ha-select-radius-lg',
  placeholderColor: '--ha-select-placeholder-color',
  focusBorder: '--ha-select-focus-border',
  focusRing: '--ha-select-focus-ring',
  focusRingOffset: '--ha-select-focus-ring-offset',
  errorBorder: '--ha-select-error-border',
  errorColor: '--ha-select-error-color',
  disabledBg: '--ha-select-disabled-bg',
  disabledColor: '--ha-select-disabled-color',
  disabledOpacity: '--ha-select-disabled-opacity',
  readonlyBg: '--ha-select-readonly-bg',
  readonlyBorder: '--ha-select-readonly-border',
  transitionDuration: '--ha-select-transition-duration',
  transitionEasing: '--ha-select-transition-easing',
  gap: '--ha-select-gap',

  // Panel (7)
  panelBg: '--ha-select-panel-bg',
  panelBorder: '--ha-select-panel-border',
  panelRadius: '--ha-select-panel-radius',
  panelShadow: '--ha-select-panel-shadow',
  panelMaxHeight: '--ha-select-panel-max-height',
  panelPaddingY: '--ha-select-panel-padding-y',
  panelOffset: '--ha-select-panel-offset',

  // Option (14)
  optionColor: '--ha-select-option-color',
  optionBg: '--ha-select-option-bg',
  optionPaddingX: '--ha-select-option-padding-x',
  optionPaddingY: '--ha-select-option-padding-y',
  optionMinHeight: '--ha-select-option-min-height',
  optionFontSize: '--ha-select-option-font-size',
  optionHoverBg: '--ha-select-option-hover-bg',
  optionActiveBg: '--ha-select-option-active-bg',
  optionActiveColor: '--ha-select-option-active-color',
  optionSelectedBg: '--ha-select-option-selected-bg',
  optionSelectedColor: '--ha-select-option-selected-color',
  optionSelectedFontWeight: '--ha-select-option-selected-font-weight',
  optionDisabledColor: '--ha-select-option-disabled-color',
  optionDisabledOpacity: '--ha-select-option-disabled-opacity',
} as const;
