export const PA_BUTTON_TOKENS = {
  bg: '--pa-button-bg',
  color: '--pa-button-color',
  border: '--pa-button-border',
  radius: '--pa-button-radius',
  gap: '--pa-button-gap',
  fontFamily: '--pa-button-font-family',
  fontWeight: '--pa-button-font-weight',
  lineHeight: '--pa-button-line-height',
  paddingSm: '--pa-button-padding-sm',
  paddingMd: '--pa-button-padding-md',
  paddingLg: '--pa-button-padding-lg',
  fontSm: '--pa-button-font-sm',
  fontMd: '--pa-button-font-md',
  fontLg: '--pa-button-font-lg',
  minHeightSm: '--pa-button-min-height-sm',
  minHeightMd: '--pa-button-min-height-md',
  minHeightLg: '--pa-button-min-height-lg',
  /** Per-size min-width (Phase 3, additive — see design D4). */
  minWidthSm: '--pa-button-min-width-sm',
  minWidthMd: '--pa-button-min-width-md',
  minWidthLg: '--pa-button-min-width-lg',
  /** Per-size gap (Phase 3, additive — coexists with the unsized `gap` above). */
  gapSm: '--pa-button-gap-sm',
  gapMd: '--pa-button-gap-md',
  gapLg: '--pa-button-gap-lg',
  focusRing: '--pa-button-focus-ring',
  hoverBg: '--pa-button-hover-bg',
  activeBg: '--pa-button-active-bg',
  disabledBg: '--pa-button-disabled-bg',
  disabledColor: '--pa-button-disabled-color',
  disabledOpacity: '--pa-button-disabled-opacity',
  solidColor: '--pa-button-solid-color',
  transitionDuration: '--pa-button-transition-duration',
  transitionEasing: '--pa-button-transition-easing',
  loadingColor: '--pa-button-loading-color',
  spinnerSize: '--pa-button-spinner-size',
  spinnerBorder: '--pa-button-spinner-border',
  spinnerDuration: '--pa-button-spinner-duration',
  /** Visually-hidden screen reader only — width, height, and margin tokens */
  srOnlyWidth: '--pa-button-sr-only-width',
  srOnlyHeight: '--pa-button-sr-only-height',
  srOnlyMargin: '--pa-button-sr-only-margin',
} as const;
