export const PA_BUTTON_TOKENS = {
  bg: '--pa-button-bg',
  color: '--pa-button-color',
  border: '--pa-button-border',
  radius: '--pa-button-radius',
  paddingSm: '--pa-button-padding-sm',
  paddingMd: '--pa-button-padding-md',
  paddingLg: '--pa-button-padding-lg',
  fontSm: '--pa-button-font-sm',
  fontMd: '--pa-button-font-md',
  fontLg: '--pa-button-font-lg',
  minHeight: '--pa-button-min-height',
  focusRing: '--pa-button-focus-ring',
  hoverBg: '--pa-button-hover-bg',
  activeBg: '--pa-button-active-bg',
  disabledBg: '--pa-button-disabled-bg',
  disabledColor: '--pa-button-disabled-color',
  loadingColor: '--pa-button-loading-color',
  spinnerSize: '--pa-button-spinner-size',
} as const;
