export const HA_BUTTON_TOKENS = {
  bg: '--ha-button-bg',
  color: '--ha-button-color',
  border: '--ha-button-border',
  radius: '--ha-button-radius',
  gap: '--ha-button-gap',
  fontFamily: '--ha-button-font-family',
  fontWeight: '--ha-button-font-weight',
  lineHeight: '--ha-button-line-height',
  paddingSm: '--ha-button-padding-sm',
  paddingMd: '--ha-button-padding-md',
  paddingLg: '--ha-button-padding-lg',
  fontSm: '--ha-button-font-sm',
  fontMd: '--ha-button-font-md',
  fontLg: '--ha-button-font-lg',
  minHeightSm: '--ha-button-min-height-sm',
  minHeightMd: '--ha-button-min-height-md',
  minHeightLg: '--ha-button-min-height-lg',
  /** Per-size min-width (Phase 3, additive — see design D4). */
  minWidthSm: '--ha-button-min-width-sm',
  minWidthMd: '--ha-button-min-width-md',
  minWidthLg: '--ha-button-min-width-lg',
  /** Per-size gap (Phase 3, additive — coexists with the unsized `gap` above). */
  gapSm: '--ha-button-gap-sm',
  gapMd: '--ha-button-gap-md',
  gapLg: '--ha-button-gap-lg',
  focusRing: '--ha-button-focus-ring',
  focusRingOffset: '--ha-button-focus-ring-offset',
  hoverBg: '--ha-button-hover-bg',
  activeBg: '--ha-button-active-bg',
  disabledBg: '--ha-button-disabled-bg',
  disabledColor: '--ha-button-disabled-color',
  disabledOpacity: '--ha-button-disabled-opacity',
  solidColor: '--ha-button-solid-color',
  transitionDuration: '--ha-button-transition-duration',
  transitionEasing: '--ha-button-transition-easing',
  loadingColor: '--ha-button-loading-color',
  spinnerSize: '--ha-button-spinner-size',
  spinnerBorder: '--ha-button-spinner-border',
  spinnerDuration: '--ha-button-spinner-duration',
  /** Visually-hidden screen reader only — width, height, and margin tokens */
  srOnlyWidth: '--ha-button-sr-only-width',
  srOnlyHeight: '--ha-button-sr-only-height',
  srOnlyMargin: '--ha-button-sr-only-margin',
} as const;
